from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd
from pydantic import BaseModel, Field

REPO_ROOT = Path(__file__).resolve().parents[1]
PROMPTS_DIR = REPO_ROOT / "prompts"

##########################################
# DATA CONTAINERS
##########################################


# Pydantic model used to define the JSON schema required by the API to enforce the structured output
class FairnessReport(BaseModel):
    """Both text and latex agree on the content"""

    text: str = Field(description="Plain text report.")
    latex: str = Field(description="Standalone LaTeX document.")


# Data container for the LLM report result, including text, LaTeX, and usage information
@dataclass(frozen=True)
class LLMReportResult:
    """
    LLM report result

    Args:
        text: The plain text report generated by the LLM.
        latex: The LaTeX report generated by the LLM.
        usage: The usage information returned by the LLM API (if any).
    """

    text: str
    latex: str
    usage: Any = None

    def __iter__(self):
        return iter((self.text, self.latex, self.usage))


##########################################
# UTILS
##########################################
def load_prompt(name: str) -> str:
    """
    Load a prompt from the prompts directory.

    Args:
        name: The name of the prompt file to load.

    Returns:
        The contents of the prompt file as a string.
    """
    return (PROMPTS_DIR / name).read_text(encoding="utf-8")


def prepare_llm_payload_general(
    *,
    dataset_name: str,
    X: str,
    Y: str,
    W: Sequence[str] | None = None,
    Z: Sequence[str] | None = None,
    x0: Any = None,
    x1: Any = None,
    y_target: Any = None,
    results: dict[str, Any] | list[dict[str, Any]] | None = None,
    stepwise_results: Sequence[dict[str, Any]] | None = None,
    variable_metadata: dict[str, Any] | None = None,
    cont_results: Sequence[dict[str, Any]] | None = None,
    state_names: dict[str, Any] | None = None,
    graph_edges: Sequence[tuple[str, str]] | None = None,
    checks: dict[str, Any] | None = None,
    notes: Sequence[str] | None = None,
    ie_decomp: dict[str, Any] | None = None,
    se_decomp: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Prepare a payload for LLM summarization.

    Args:
        dataset_name: Name of the dataset.
        X: Protected variable.
        Y: Outcome variable.
        W: Mediator variables.
        Z: Spurious features.
        x0: Value of X for the reference group.
        x1: Value of X for the target group.
        y_target: Value of Y for the target outcome.
        results: General results of the analysis.
        stepwise_results: Stepwise results of the analysis.
        variable_metadata: Metadata about the variables.
        cont_results: Continuous results of the analysis.
        state_names: Names of the states for categorical variables.
        graph_edges: Edges of the causal graph.
        checks: Checks performed during the analysis.
        notes: Additional notes or comments.
        ie_decomp: Individual effect decomposition results.
        se_decomp: Spurious effect decomposition results.

    Returns:
        A dictionary representing the payload for LLM summarization.
    """
    W = list(W or [])
    Z = list(Z or [])
    variable_metadata = dict(variable_metadata or {})
    checks = dict(checks or {})
    stepwise_results = list(stepwise_results or [])
    cont_results = list(cont_results or [])
    ie_decomp = dict(ie_decomp or {})
    se_decomp = dict(se_decomp or {})

    if isinstance(results, pd.Series):
        results = results.to_dict()
    elif isinstance(results, pd.DataFrame):
        results = results.to_dict(orient="records")

    if isinstance(variable_metadata, pd.Series):
        variable_metadata = variable_metadata.to_dict()

    if isinstance(state_names, pd.Series):
        state_names = state_names.to_dict()

    payload: dict[str, Any] = {
        "dataset": dataset_name,
        "causal_query": {
            "X": X,
            "Y": Y,
            "W": W,
            "Z": Z,
            "x0": x0,
            "x1": x1,
            "y_target": y_target,
        },
        "variable_metadata": variable_metadata,
        "state_names": state_names,
        "graph_edges": list(graph_edges) if graph_edges is not None else None,
        "results": results,
        "continuous_results": cont_results,
        "ie_decomp": ie_decomp,
        "se_decomp": se_decomp,
        "checks": checks,
        "notes": list(notes) if notes is not None else None,
    }

    if stepwise_results:
        payload["stepwise_results"] = stepwise_results

    return payload


def payload_to_json(payload: dict[str, Any], indent: int = 2) -> str:
    """Convert the payload dictionary to a JSON-formatted string with indentation."""
    return json.dumps(payload, indent=indent, ensure_ascii=False, default=str)


###########################################
# LLM SUMMARIZATION
###########################################


def summarize_fairmind(
    results: dict[str, Any],
    client: Any,
    model: str,
    prompt_path: str,
    effort: str = "high",
) -> LLMReportResult:
    """
    Summarize the fairness decomposition results using the LLM.

    Args:
        results: The fairness decomposition results to summarize.
        client: The LLM client to use for summarization.
        model: The LLM model to use for summarization.
        prompt_path: The path to the prompt file to use for summarization.
        effort: The reasoning effort level ("low", "medium", or "high").

    Returns:
        An LLMReportResult containing the summarized text, LaTeX, and usage information.
    """
    system_prompt = load_prompt(prompt_path)

    if "stepwise_results" in results:
        system_prompt += "\n\nInclude a 'Stepwise Effects Across Ordered Levels of X' section detailing the stepwise effects."

    user_prompt = (
        "Here are the fairness decomposition results in JSON:\n\n"
        + payload_to_json(results)
    )

    resp = client.responses.parse(
        model=model,
        reasoning={"effort": effort},
        instructions=system_prompt,
        text_format=FairnessReport,
        input=[
            {
                "role": "user",
                "content": [{"type": "input_text", "text": user_prompt}],
            }
        ],
    )

    return LLMReportResult(
        text=resp.output_parsed.text, latex=resp.output_parsed.latex, usage=resp.usage
    )


def _format_variable_roles(names: Sequence[Any], values: Sequence[Any] | None) -> str:
    """Format a list of variable names, with their relevant levels if given."""
    if not names:
        return "None"
    formatted = ", ".join(str(name) for name in names)
    if values:
        formatted += f" (relevant levels: {', '.join(str(v) for v in values)})"
    return formatted


def summarize_llm_only(
    x: Any = None,
    y: Any = None,
    x0: Any = None,
    x1: Any = None,
    y_value: Any = None,
    z: Sequence[Any] | None = None,
    w: Sequence[Any] | None = None,
    w_values: Sequence[Any] | None = None,
    z_values: Sequence[Any] | None = None,
) -> tuple[str, str]:
    """
    Build the prompts for the LLM-only fairness decomposition. The dataset
    itself is passed out-of-band (code-interpreter file); the prompts only
    carry the column roles.

    Args:
        x: The protected variable.
        y: The outcome variable.
        x0: The value of the protected variable for the first group.
        x1: The value of the protected variable for the second group.
        y_value: The value of the outcome variable.
        z: The spurious features.
        w: The mediator variables.
        w_values: The relevant levels of the mediator variables.
        z_values: The relevant levels of the spurious features.

    Returns:
        A tuple containing the system prompt and user prompt.
    """
    missing = [
        name
        for name, val in [
            ("x", x),
            ("y", y),
            ("x0", x0),
            ("x1", x1),
            ("y_value", y_value),
        ]
        if val is None
    ]
    if missing:
        raise ValueError(f"Missing required column roles: {', '.join(missing)}")

    z = list(z or [])
    w = list(w or [])

    system_prompt = load_prompt("only_llm_v2.txt")

    user_prompt = f"""
You are given a dataset file (a tabular dataset, e.g. CSV or plain-text table). Load it with the code interpreter and inspect the columns before computing anything.

Column roles:
- X (protected variable): {x}, comparing x0={x0} vs x1={x1}
- Y (outcome attribute): {y}, outcome value of interest y={y_value}
- Z (spurious features / confounders): {_format_variable_roles(z, z_values)}
- W (mediator variables): {_format_variable_roles(w, w_values)}

Your task:
1. Load and inspect the dataset.
2. Compute the fairness decomposition according to Plecko and Bareinboim theory, both general and X-Z specific effects.
3. Produce a structured report.
"""

    return system_prompt, user_prompt


def generate_report_from_file_id(
    file_id: str,
    client: Any,
    model: str = "gpt-5.4-nano",
    prompt_kwargs: dict[str, Any] | None = None,
    effort: str = "high",
) -> LLMReportResult:
    """
    Generate a fairness decomposition report using the LLM, given a file ID.

    The dataset is made available to the model through the code-interpreter
    tool; only the column roles (from ``prompt_kwargs``) travel in the prompt.

    Args:
        file_id: The ID of the uploaded file containing the dataset.
        client: The LLM client to use for generation.
        model: The LLM model to use.
        prompt_kwargs: Keyword arguments for `summarize_llm_only` describing
            the column roles (x, y, x0, x1, y_value, z, w, ...).
        effort: The reasoning effort level ("low", "medium", or "high").

    Returns:
        An LLMReportResult containing the generated text, LaTeX, and usage information.
    """
    prompt_kwargs = prompt_kwargs or {}
    _validate_prompt_kwargs(prompt_kwargs)

    system_prompt, user_prompt = summarize_llm_only(**prompt_kwargs)

    resp = client.responses.parse(
        model=model,
        reasoning={"effort": effort},
        instructions=system_prompt,
        text_format=FairnessReport,
        tools=[
            {
                "type": "code_interpreter",
                "container": {"type": "auto", "file_ids": [file_id]},
            },
        ],
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": user_prompt},
                ],
            }
        ],
    )

    return LLMReportResult(
        text=resp.output_parsed.text, latex=resp.output_parsed.latex, usage=resp.usage
    )


def generate_report_from_dataset(
    data_path: str | Path,
    client: Any,
    model: str = "gpt-5.4-nano",
    prompt_kwargs: dict[str, Any] | None = None,
    effort: str = "high",
) -> LLMReportResult:
    """
    Upload a local dataset file and generate a fairness decomposition report.

    Convenience wrapper around `generate_report_from_file_id` that handles the
    file upload, so callers only need a path and the column roles.

    Args:
        data_path: Path to the local dataset file (CSV or similar text table).
        client: The LLM client to use for upload and generation.
        model: The LLM model to use.
        prompt_kwargs: Keyword arguments for `summarize_llm_only` describing
            the column roles (x, y, x0, x1, y_value, z, w, ...).
        effort: The reasoning effort level ("low", "medium", or "high").

    Returns:
        An LLMReportResult containing the generated text, LaTeX, and usage information.
    """
    with open(data_path, "rb") as f:
        uploaded = client.files.create(file=f, purpose="assistants")

    _validate_prompt_kwargs(prompt_kwargs)

    return generate_report_from_file_id(
        uploaded.id, client, model=model, prompt_kwargs=prompt_kwargs, effort=effort
    )


def _validate_prompt_kwargs(prompt_kwargs: dict[str, Any] | None) -> None:
    """Validate the prompt_kwargs for required keys."""
    if not prompt_kwargs:
        raise ValueError("prompt_kwargs cannot be None")

    required_keys = ["x", "y", "x0", "x1", "y_value"]
    missing_keys = [key for key in required_keys if key not in prompt_kwargs]
    if missing_keys:
        raise ValueError(
            f"Missing required prompt_kwargs keys: {', '.join(missing_keys)}"
        )
